---
name: BSN (Dev)
services:
  bsn_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bsn-dev
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
    # Add healthcheck if needed
    # healthcheck:
    #   test: curl --fail http://localhost:5000/health-check || exit 1
    #   interval: 60s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
    develop:
      watch:
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: src/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
        - action: sync+restart
          path: compose-dev.yml
          target: python-starter
        - action: sync+restart
          path: .env
          target: python-starter
