[project]
name = "bsn"
version = "0.1.0"
description = ""
authors = [
    {name = "Jack Stockley", email = "jack@jstockley.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client==2.162.0",
    "python-dotenv==1.0.1",
    "peewee==3.17.9",
    "pandas==2.2.3",
    "apprise==1.9.2"
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "==0.9.7"

