[project]
name = "bsn"
version = "0.1.0"
description = ""
authors = [
    {name = "Jack Stockley", email = "jack@jstockley.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client==2.172.0",
    "python-dotenv==1.1.0",
    "peewee==3.18.2",
    "pandas==2.3.0",
    "apprise==1.9.3"
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "==0.12.3"

