name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install Latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ env.HOME }}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: poetry install --with dev
      - name: Flake8 Linting
        run: |
          poetry run flake8 better_social_notifications --count --show-source --max-line-length 120 --statistics 
          poetry run flake8 better_social_notifications --count --max-complexity=10 --max-line-length=120 --statistics
      - name: Autopep8 Linting
        run: poetry run autopep8 --dif --recursive better_social_notifications
  
  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install Latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ env.HOME }}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: poetry install --with dev
      - name: Run Tests
        run: |
          poetry run coverage run --branch -m pytest
          poetry run coverage report
          
  Deploy:
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Install Latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ env.HOME }}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: poetry install
      - name: Build & Publish to PyPi
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
